---
minimum_pre_commit_version: "4.0"
fail_fast: false
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.13
    hooks:
      - id: ruff-check
        args:
          - --fix
      - id: ruff-format
  - repo: https://github.com/bwhmather/ssort
    rev: 0.16.0
    hooks:
      - id: ssort
  - repo: local
    hooks:
      - id: deptry
        name: deptry
        description: deptry is a command line tool to check for issues with dependencies in a Python project, such as unused or missing dependencies.
        entry: make deptry
        language: system
        always_run: true
        pass_filenames: false
      - id: ty
        name: ty
        entry: make ty
        language: system
        types:
          - python
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: make local-tests
        language: system
        types:
          - python
        pass_filenames: false
      - id: biome-check
        name: biome-check
        entry: biome check --write --files-ignore-unknown=true --no-errors-on-unmatched
        language: system
        types: [text]
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
        args:
          - --unsafe
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
